# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterApp',
            fields=[
                ('id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('AppName', models.TextField(max_length=50)),
                ('ConsumerKey', models.TextField(max_length=100)),
                ('ConsumerToken', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterApp_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('access_token', models.TextField(max_length=100)),
                ('access_key', models.TextField(max_length=100)),
                ('screen_name', models.TextField(db_index=True, max_length=100)),
                ('id_int', models.IntegerField()),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('profile_pic_url', models.URLField()),
                ('followers_count', models.IntegerField()),
                ('verified', models.BooleanField()),
                ('profile_url', models.URLField()),
                ('date_joined', models.DateTimeField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.TwitterApp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='twitterapp_user',
            unique_together=set([('app', 'screen_name')]),
        ),
    ]
