# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('functions', '0002_auto_20170726_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius', models.FloatField()),
                ('radiusUnit', models.CharField(choices=[('km', 'km'), ('mi', 'mi')], default='km', max_length=2)),
                ('AppName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.TwitterApp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
