# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0003_locationsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationsearch',
            name='AppName',
        ),
        migrations.RemoveField(
            model_name='locationsearch',
            name='user',
        ),
        migrations.DeleteModel(
            name='LocationSearch',
        ),
    ]
