# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170723_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdata',
            name='consumerkey',
        ),
        migrations.RemoveField(
            model_name='applicationdata',
            name='consumersecret',
        ),
        migrations.RemoveField(
            model_name='applicationdata',
            name='id',
        ),
        migrations.AddField(
            model_name='applicationaccess',
            name='consumerkey',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='applicationaccess',
            name='consumersecret',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='applicationaccess',
            name='accesssecret',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='applicationaccess',
            name='accesstoken',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='appname',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicationdata',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
